---

mssql_installation_source: https://go.microsoft.com/fwlink/p/?linkid=866662

# Path to download installation media to
mssql_installation_path: C:\SQLInstall

# Temporary path to store downloader
mssql_temp_download_path: C:\tmp

mssql_instance_name: Test
mssql_drive: C
mssql_userdbvol_name: Userdbvol01
mssql_port: 1433

mssql_max_server_memory: 1024

mssql_os_memory_reservation: 512

mssql_total_system_memory: "{{ mssql_max_server_memory + mssql_os_memory_reservation }}"

mssql_suppress_reboot: False


mssql_base_ldap_path: "cn=Users,dc=CONTOSO,dc=com"
domain_controller: dc01

mssql_sqlsvc_account: CONTOSO\sql_svc
mssql_sqlsvc_account_pass: MyPlainTextPassWord01

mssql_agentsvc_account: CONTOSO\sql_agt
mssql_agentsvc_account_pass: MyPlainTextPassWord01

mssql_assvc_account: "{{ mssql_sqlsvc_account }}"
mssql_assvc_account_pass: "{{ mssql_sqlsvc_account_pass }}"


mssql_userdbvol_path: "{{ mssql_drive }}:\\{{ mssql_userdbvol_name }}"
mssql_db_accesspath: "{{ mssql_userdbvol_path }}\\DatabaseFiles"
mssql_logs_accesspath: "{{ mssql_userdbvol_path }}\\DatabaseLogs"

mssql_installshared_path: C:\Program Files\Microsoft SQL Server
mssql_installsharedwow_path: C:\Program Files (x86)\Microsoft SQL Server

mssql_instance_path: "C:\\Program Files\\Microsoft SQL Server\\{{ mssql_instance_name }}"

mssql_sqlinstalldata_path: "{{ mssql_db_accesspath }}\\{{mssql_instance_name }}"
mssql_sqluserdata_path: "{{ mssql_db_accesspath }}\\{{mssql_instance_name }}"
mssql_sqluserlog_path: "{{ mssql_logs_accesspath }}\\{{mssql_instance_name }}"
mssql_sqltempDB_path: "C:\\TempDBFiles\\Data\\{{mssql_instance_name }}"
mssql_sqltempDBlog_path: "C:\\TempDBFiles\\Log\\{{mssql_instance_name }}"

mssql_security_mode: sql

mssql_sa_password: "{{ mssql_sqlsvc_account_pass }}"


mssql_features: SQLENGINE,FULLTEXT,CONN

mssql_collation: SQL_Latin1_General_CP1_CI_AS

mssql_browsersvc_mode: Automatic

mssql_sysadmin_accounts: 
  - CONTOSO\Domain Admins
  - CONTOSO\Administrator

mssql_asadmin_accounts: "{{ mssql_sysadmin_accounts }}"

mssql_max_degree_of_parallelism: 0

mssql_min_server_memory: 0
